<!DOCTYPE html>
<html lang="pt-br">

<head>
    <!-- Meta tags Obrigatórias -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title><?php echo $this->getPageTitle() ?></title>
</head>

<body>
    <?php $this->content() ?>

    <!-- JavaScript (Opcional) -->
    <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
<script>
    document.getElementById('inciar-painel').addEventListener('click', function() {
        let strWindowFeatures = "menubar=no,location=no,resizable=no,scrollbars=no,status=no,toolbar=no";
        window.open("painel/", "PainelMaratona_WindowName", strWindowFeatures);

        return;
    });

    $text = 'Modal para varificar id: ';

    //Busca as resposta
    $('#modal-confirm-respsta').on('show.bs.modal', function(event) {
        // Ganbiarra para lipar o text
        document.getElementById('message-text').value = 'Click no botão charge para carregar a pergunta';

        var button = $(event.relatedTarget) // Botão que acionou o modal
        var recipient = button.data('whatever') // Extrai informação dos atributos data-*
        // Se necessário, você pode iniciar uma requisição AJAX aqui e, então, fazer a atualização em um callback.
        // Atualiza o conteúdo do modal. Nós vamos usar jQuery, aqui. No entanto, você poderia usar uma biblioteca de data binding ou outros métodos.
        var modal = $(this)
        modal.find('.modal-title').text('Resposta da pergunta: ' + recipient)
        modal.find('.modal-body input').val(recipient)
        $('#recipient-type').val('undefined');
        $('#recipient-score').val('undefined');

    });

    $('#modal-edit-fila').on('show.bs.modal', function(event) {
        // Ganbiarra para lipar o text
        document.getElementById('message-text').value = 'Click no botão charge para carregar a pergunta';

        var button = $(event.relatedTarget) // Botão que acionou o modal
        var recipient = button.data('whatever') // Extrai informação dos atributos data-*
        // Se necessário, você pode iniciar uma requisição AJAX aqui e, então, fazer a atualização em um callback.
        // Atualiza o conteúdo do modal. Nós vamos usar jQuery, aqui. No entanto, você poderia usar uma biblioteca de data binding ou outros métodos.
        var modal = $(this)
        modal.find('.modal-title').text('Modal para varificar id: ' + recipient)
        modal.find('.modal-body input').val(recipient)
        $('#recipient-type').val('undefined');
        $('#recipient-score').val('undefined');

        let ajax = new XMLHttpRequest();
        ajax.onreadystatechange = function() {
            if (ajax.readyState == 4 && ajax.status == 200) {
                //let $result = JSON.parse(ajax.response);
                console.log(ajax.response)
                if (ajax.response) {                    
                    document.querySelector('#modal-edit-fila-nullQuestion').innerText = 'Activate';
                    jQuery('#modal-edit-fila-nullQuestion').attr('class','btn btn-dark');
                    jQuery('#modal-edit-fila-backPainel').attr('class','btn btn-light');                  
                    jQuery('#modal-edit-fila-backPainel').attr('disabled',true);                    
                    return;
                }
                document.querySelector('#modal-edit-fila-nullQuestion').innerText = 'Override';
                jQuery('#modal-edit-fila-backPainel').attr('class','btn btn-success');
                jQuery('#modal-edit-fila-backPainel').attr('disabled',false); 
                jQuery('#modal-edit-fila-nullQuestion').attr('class','btn btn-warning');
                
                return;
            }
        }
        ajax.open("GET", '/anular/' + recipient + '/show', true);
        ajax.send();

    })

    $('#modal-edit-perggroup').on('show.bs.modal', function(event) {
        let button = $(event.relatedTarget) // Button that triggered the modal 
        let recipient = button.data('whatever') // Extract info from data-* attributes
        // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
        // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
        let modal = $(this)
        modal.find('.modal-title').text('New message to ' + recipient)
        modal.find(".modal-body #modal-groups-input-id").val(recipient)
        modal.find(".modal-body #modal-groups-input-content").text('Click on the "Charge" button to bring information about the issue.')
    })

    $('#modal-punishment-groups').on('show.bs.modal', function(event) {
        let button = $(event.relatedTarget) // Button that triggered the modal 
        let recipient = button.data('whatever')
        let idGroups = $('#grupo-input-group-id').val();
        let nameGroups = $('#backgo-input-group-name').val();
        let modal = $(this)
        modal.find('.modal-title').text('punishing the group: ' + nameGroups)
        modal.find(".modal-body #modal-punishment-groups-input-id").val(idGroups)
        // Reset
        $('#modal-punishment-groups-input-value').val('');
        $('#modal-punishment-groups-text-content').val('');
    })

    $('#modal-addPunctuation').on('show.bs.modal', function(event) {
        let button = $(event.relatedTarget) // Button that triggered the modal 
        let recipient = button.data('whatever')
        let idGroups = $('#grupo-input-group-id').val();
        let nameGroups = $('#backgo-input-group-name').val();
        let modal = $(this)
        modal.find('.modal-title').text('punishing the group: ' + nameGroups)
        modal.find(".modal-body #modal-addPunctuation-input-id").val(idGroups)

        $('#mmodal-addPunctuation-input-value').val('');
        $('#modal-addPunctuation-text-content').val('');
    })

    $('#modal-control-panel').on('show.bs.modal', function() {
        var ajax = new XMLHttpRequest();
        ajax.onreadystatechange = function() {
            if (ajax.readyState == 4 && ajax.status == 200) {
                let $result = JSON.parse(ajax.response).event;
                for (let i = 0; i < $result.length; i++) {
                    const element = String($result[i]);
                    switch (element) {
                        case 'end-scoreboard':
                            $('#status-painel-modal').text('Tempo limite finalizado.');
                            return;
                        default:
                            $('#status-painel-modal').text('Painel foi iniciado.');
                            return;
                    }

                }

                return true;
            }
            return false;
        }
        ajax.open('GET', '/painel/show?df=1,4', true);
        ajax.send();
    })
</script>

</html>