<nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-center">
  <ul class="navbar-nav ">

    <li class="nav-item">
      <a class="nav-link" href="#"></a>
    </li>

    <?php if ($this->auth->check()) : ?>
      <li class="nav-item">
        <a class="nav-link active" href="/adm">Administrador</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" href="/logout">Logout</a>
      </li>
    <?php else : ?>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Administrador</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" href="/login">Login</a>
      </li>
    <?php endif ?>
  </ul>
</nav>